// <auto-generated />
using System;
using FoundersDesk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoundersDesk.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224205342_Seed_Final")]
    partial class Seed_Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FoundersDesk.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FoundersDesk.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 101,
                            CreatedAt = new DateTime(2025, 12, 24, 20, 53, 40, 600, DateTimeKind.Utc).AddTicks(6112),
                            Email = "intern1@example.com",
                            IsActive = true,
                            PasswordHash = "+AfXPPmsbrRkF+x8RH5i+EofgowXTUkVVImFJw7sy7w=",
                            Role = 1,
                            Username = "intern1"
                        },
                        new
                        {
                            UserId = 102,
                            CreatedAt = new DateTime(2025, 12, 24, 20, 53, 40, 600, DateTimeKind.Utc).AddTicks(7828),
                            Email = "vendor1@example.com",
                            IsActive = true,
                            PasswordHash = "Pplu78JXGSTcBXXPb5SF8DnElLUX7/+HLQM0or+ao4k=",
                            Role = 2,
                            Username = "vendor1"
                        });
                });

            modelBuilder.Entity("FoundersDesk.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            Category = "orientation",
                            Description = "Platform overview",
                            DisplayOrder = 1,
                            Icon = "🎉",
                            IsActive = true,
                            RoleType = "general",
                            Title = "Welcome to Founder's Desk",
                            VideoUrl = "https://youtu.be/1"
                        },
                        new
                        {
                            VideoId = 2,
                            Category = "orientation",
                            Description = "Rules & conduct",
                            DisplayOrder = 2,
                            Icon = "📘",
                            IsActive = true,
                            RoleType = "general",
                            Title = "Intern Guidelines",
                            VideoUrl = "https://youtu.be/2"
                        },
                        new
                        {
                            VideoId = 3,
                            Category = "projects",
                            Description = "What you'll work on",
                            DisplayOrder = 3,
                            Icon = "📂",
                            IsActive = true,
                            RoleType = "general",
                            Title = "Current Projects",
                            VideoUrl = "https://youtu.be/3"
                        },
                        new
                        {
                            VideoId = 4,
                            Category = "culture",
                            Description = "Our values",
                            DisplayOrder = 4,
                            Icon = "🤝",
                            IsActive = true,
                            RoleType = "general",
                            Title = "Company Culture",
                            VideoUrl = "https://youtu.be/4"
                        },
                        new
                        {
                            VideoId = 5,
                            Category = "technical",
                            Description = "Tools & frameworks",
                            DisplayOrder = 5,
                            Icon = "💻",
                            IsActive = true,
                            RoleType = "technical",
                            Title = "Tech Stack Intro",
                            VideoUrl = "https://youtu.be/5"
                        },
                        new
                        {
                            VideoId = 6,
                            Category = "technical",
                            Description = "Best practices",
                            DisplayOrder = 6,
                            Icon = "🧠",
                            IsActive = true,
                            RoleType = "technical",
                            Title = "Coding Standards",
                            VideoUrl = "https://youtu.be/6"
                        },
                        new
                        {
                            VideoId = 7,
                            Category = "non-technical",
                            Description = "Client & team communication",
                            DisplayOrder = 7,
                            Icon = "🗣️",
                            IsActive = true,
                            RoleType = "non-technical",
                            Title = "Communication Skills",
                            VideoUrl = "https://youtu.be/7"
                        },
                        new
                        {
                            VideoId = 8,
                            Category = "non-technical",
                            Description = "Work smart",
                            DisplayOrder = 8,
                            Icon = "⏱️",
                            IsActive = true,
                            RoleType = "non-technical",
                            Title = "Time Management",
                            VideoUrl = "https://youtu.be/8"
                        },
                        new
                        {
                            VideoId = 11,
                            Category = "vendor",
                            Description = "How vendors use the platform",
                            DisplayOrder = 1,
                            Icon = "🏢",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Vendor Overview",
                            VideoUrl = "https://youtu.be/9"
                        },
                        new
                        {
                            VideoId = 12,
                            Category = "vendor",
                            Description = "Post openings + requirements",
                            DisplayOrder = 2,
                            Icon = "📄",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Adding Requirements",
                            VideoUrl = "https://youtu.be/10"
                        },
                        new
                        {
                            VideoId = 13,
                            Category = "vendor",
                            Description = "Allocate work to interns",
                            DisplayOrder = 3,
                            Icon = "🗂️",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Assign Projects",
                            VideoUrl = "https://youtu.be/11"
                        },
                        new
                        {
                            VideoId = 14,
                            Category = "vendor",
                            Description = "Monitor activities & progress",
                            DisplayOrder = 4,
                            Icon = "📊",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Track Intern Work",
                            VideoUrl = "https://youtu.be/12"
                        },
                        new
                        {
                            VideoId = 15,
                            Category = "vendor",
                            Description = "Chat & meetings",
                            DisplayOrder = 5,
                            Icon = "💬",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Communicate with Interns",
                            VideoUrl = "https://youtu.be/13"
                        },
                        new
                        {
                            VideoId = 16,
                            Category = "vendor",
                            Description = "Billing + agreements",
                            DisplayOrder = 6,
                            Icon = "💼",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Payment & Contracts",
                            VideoUrl = "https://youtu.be/14"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
