// <auto-generated />
using System;
using FoundersDesk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoundersDesk.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224170902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FoundersDesk.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FoundersDesk.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoundersDesk.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            Category = "orientation",
                            Description = "Company intro",
                            DisplayOrder = 1,
                            Icon = "🎯",
                            IsActive = true,
                            RoleType = "general",
                            Title = "Welcome to Founder's Desk",
                            VideoUrl = "https://example.com/video1.mp4"
                        },
                        new
                        {
                            VideoId = 2,
                            Category = "orientation",
                            Description = "Rules & guidelines",
                            DisplayOrder = 2,
                            Icon = "📚",
                            IsActive = true,
                            RoleType = "general",
                            Title = "Company Policies",
                            VideoUrl = "https://example.com/video2.mp4"
                        },
                        new
                        {
                            VideoId = 3,
                            Category = "orientation",
                            Description = "Working together",
                            DisplayOrder = 3,
                            Icon = "🤝",
                            IsActive = true,
                            RoleType = "general",
                            Title = "Team Collaboration",
                            VideoUrl = "https://example.com/video3.mp4"
                        },
                        new
                        {
                            VideoId = 14,
                            Category = "platform",
                            Description = "Vendor onboarding",
                            DisplayOrder = 1,
                            Icon = "🚀",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Platform Introduction",
                            VideoUrl = "https://example.com/video14.mp4"
                        },
                        new
                        {
                            VideoId = 15,
                            Category = "platform",
                            Description = "Vendor app usage",
                            DisplayOrder = 2,
                            Icon = "📱",
                            IsActive = true,
                            RoleType = "vendor",
                            Title = "Using the App",
                            VideoUrl = "https://example.com/video15.mp4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
